create table if not exists public.rsvps (
 id bigint generated by default as identity primary key,
 nome text not null,
 resposta text not null check (resposta in ('Vai','Não vai')),
 created_at timestamptz not null default now()
);
alter table public.rsvps enable row level security;
create policy "public can insert rsvps" on public.rsvps for insert to anon
with check (char_length(trim(nome)) between 2 and 100);
create policy "authenticated can read rsvps" on public.rsvps for select to authenticated
using (true);
-- Depois: Supabase > Authentication > Users > Add user
-- Crie o e-mail/senha que será usado no dashboard.
